name: Static Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: '1.20.x'

    - name: Get dependencies
      run: |
        sudo apt-get update && sudo apt-get install gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
        go install golang.org/x/tools/cmd/goimports@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install honnef.co/go/tools/cmd/staticcheck@v0.4.2
        go install github.com/mattn/goveralls@latest

    - name: Cleanup repository
      run: rm -rf vendor/

    - name: Vet
      run: go vet -tags ci ./...

    - name: Goimports
      run: test -z "$(goimports -e -d . | tee /dev/stderr)"

    - name: Gocyclo
      run: gocyclo -over 30 .

    - name: Staticcheck
      run: staticcheck ./...

    - name: Update coverage
      run: |
        set -e
        go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
        coverage=`go tool cover -func coverage.out | grep total | tr -s '\t' | cut -f 3 | grep -o '[^%]*'`
        if (( $(echo "$coverage < 63" | bc) )); then echo "Test coverage lowered"; exit 1; fi

    - name: Update PR Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
